### ISSUE TITLE
A question about PRAM result

### ISSUE THREAD

**Issue by zhangzhiyangcs** [pliu55/PRAM_paper#1]
Hi, I used the PRAM pipeline to predict the intergenic transcripts including 300 plant samples transcipts data. There are
20,313  transcript models grouped into 12,019 gene models. Then I added this intergenic gtf into my genome anottation gtf to quantified each samples' gene TPM by using STAR to align reads and Stringtie to calculate the value of TPM. After that, I found there are 5,000 novel intergenic transcripts got 0 TPM in any samples. I  checked the data that you quantified in isoforms.tpm.gz. It is also have nearly 900  novel intergenic transcripts got 0 TPM in any samples. But it is much better than me.
I want to ask why PRAM pipeline produce these 0 TPM intergenic transcripts. And, How you quantified your intergenic transcipts?  My results looked uncredible.
Thank you very much.

**Comment by pliu55** [comment]
Hi @zhangzhiyangcs,

Thank you for using PRAM (and be the first to open an issue in this repository 🥇 ).

We also observed 0 TPM for predicted transcript models in our study.  In our case study reported in the manuscript, we found that it is because Cufflinks built transcript models from RNA-seq fragment that is incompatible with transcript's splice structure.  As a result, when quantifying this transcript model, that RNA-seq fragment will not be aligned to it and therefore this transcript model will have 0 TPM.  We presented an example in our manuscript's Supplemental Material's Supplementary Note 3 and Supplementary Figure 22 on [bioRxiv](https://www.biorxiv.org/content/biorxiv/early/2019/05/13/636282.1/DC1/embed/media-1.pdf?download=true), which will be available on Genome Research's website next month (with different numbering though).

I have not seen your data, so I cannot identify what would be the reason for that, but I suspect that it could be the same as the one reported in our manuscript.  If you would like to find out why, you may perform a similar analysis as our Supplementary Figure 22 by loading one transcript model with 0 TPM as well as aligned RNA-seq data into a genome browser for diagnosis.  I quantified transcripts using the same approach as yours except with STAR+RSEM instead of STAR+StringTie.

On the other hand, if your main goal is to predict unannotated transcripts, I would recommend to ignore those with 0 TPM and focus on the ones with high TPMs.  The main idea of PRAM is using a large number of public available RNA-seq data sets to predict transcript models and then narrowing down the list either using expression quantification (i.e., your current approach) or genomic data relevant to user's study (as presented in our manuscript).

Best,
Peng

**Comment by zhangzhiyangcs** [comment]
Thank you replied me immediately. I attended a academic conference recently and didn't notice your replication. I am sorry to this. I will try the pipeline with STAR and RSEM to find if there is difference.
My goal is to dig out the new unanotated transcripts and I pay close attention to the structure of these transcripts. I found a issue that the new unanotated transcripts translate to the protein properly with many termination codons. To deal with this problem, I extended 100bp both in the upstream and the downstream of the new transcipts. Then I get Complete ORF (Open Reading Frame) in above coordinations and tranlaste to the protein for blasting with the  
related species. Interestly, I indeedly found some highly identity new genes.  But I still have a quesion that I predict ORF is properly. This gene maybe the lncRNA that counld't translate to the protein. Maybe I could loading the transcript model aligned RNA-seq data into a genome browser for diagnosis. Do you have any advisions? Thank you again.

**Comment by pliu55** [comment]
Hi @zhangzhiyangcs 

There is totally no need to feel sorry for late reply.  The protein-coding potential of PRAM-predicted transcripts is indeed a very interesting topic and I have learned a lot from one of our manuscript's reviewers.   

There are multiple ways to check if a predicted transcript could be protein-coding:
- BLAST.  But do examine BLAST-matched hits since many of them could be hypothetical proteins.
- ORF prediction by [ORFFinder](https://www.ncbi.nlm.nih.gov/orffinder/)
- PhyloCSF: here is [its latest paper](https://genome.cshlp.org/content/early/2019/11/13/gr.246462.118) which I found very helpful.  Please remember to try all the three frame-shifts on your transcripts 

Hope the above is useful.  There is one Supplementary Note in our manuscript devoted specifically to protein-coding potential evaluation.  Unfortunately, the Supplementary Material won't be available online on Genome Research until next month. 

Best,
Peng

**Comment by zhangzhiyangcs** [comment]
It is very constructive suggestion. I will try and look forward to your the Supplementary Material next month.
